### ISSUE TITLE
Dupe when using with gravestones.

### ISSUE THREAD

**Issue by Panderine** [chronosacaria/SaveGearOnDeath#1]
Hi, If a server is using gravestones for the other half of the inventory, all the hotbar and equipped items are dupped. Is it possible to make them compatible?

**Comment by chronosacaria** [comment]
Oh whoops. I hadn't really considered that. I'll have to look into that. Thanks for letting me know, Panderine!

**Comment by IdrisQe** [comment]
Is compatability with grave mods planned for the future?

**Comment by HaXrDEV** [comment]
> Is compatability with grave mods planned for the future?

Would like to know as well. Would be huge.
